on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: fleet-test
  AWS_IAM_ROLE: arn:aws:iam::160035666661:role/github-actions-role
  TF_ACTIONS_WORKING_DIR: infrastructure/dogfood/terraform/aws

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout@v2


defaults:
  run:
    working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}

jobs:
  deploy:
    name: Deploy Fleet Dogfood Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{env.AWS_IAM_ROLE}}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.4
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Workspace
        id: workspace
        run: terraform workspace new fleet && terraform workspace select fleet
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - run: echo ${{ steps.validate.outputs.stdout}}
      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
